CREATE TABLE IF NOT EXISTS post (
  id INT NOT NULL AUTO_INCREMENT,
  texto TEXT NOT NULL,
  voto INT NOT NULL DEFAULT 0,
  data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao DATETIME ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;